FROM node:24-alpine

ENV CI=true \
    NG_CLI_ANALYTICS=ci \
    CHOKIDAR_USEPOLLING=1

WORKDIR /app

COPY package*.json ./

RUN npm ci

EXPOSE 4200

CMD ["npx","ng","serve","--host","0.0.0.0","--port","4200","--live-reload","true","--poll","2000"]
