FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY pom.xml .

RUN mvn -q dependency:go-offline

# src is stored as volume

EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=docker"]