FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY mvnw mvnw.cmd ./
RUN chmod +x mvnw
COPY .mvn .mvn
COPY pom.xml ./

RUN ./mvnw -q -DskipTests dependency:go-offline

CMD ["./mvnw", "spring-boot:run"]
