FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt watchfiles==0.21.0

COPY src ./src

CMD ["watchfiles", "--filter", "python", "--target-type", "command", "python -m src.main", "src"]
